### ISSUE TITLE
phonegap 用不了

### ISSUE THREAD

**Issue by cheft** [iVanPan/Cordova_QQ#1]
phonegap 用不了

**Comment by iVanPan** [comment]
@cheft 有报错吗？是iOS 还是android？

**Comment by iVanPan** [comment]
@cheft  我刚刚测试了一下 android 和iOS 登录 和分享都是可以的，我用的是cordova 最新的版本，如果是iOS的话 要注意在工程info里面 URL Types有没有添加成功，因为cordova有个bug https://issues.apache.org/jira/browse/CB-8007

**Comment by stephenyaoshun** [comment]
js报错
Uncaught SyntaxError: Unexpected token ILLEGAL

用的这段代码
var checkClientIsInstalled ＝ 1;//default is 0,only for iOS
                YCQQ.ssoLogin(function(args){
                        alert(2222)
                         //alert(args.access_token);
                         //alert(args.userid);
                      },function(failReason){
                         alert("failed")
                         console.log(failReason);
                },checkClientIsInstalled);

**Comment by iVanPan** [comment]
@fengfangqian  不好意思给出的代码中var checkClientIsInstalled = 1; 这句代码等号是中文字符，有问题，修改一下就应该好了

**Comment by stephenyaoshun** [comment]
@iVanPan 现在报"Uncaught ReferenceError: YCQQ is not defined"

```
    <script>
        var checkClientIsInstalled = 1;//default is 0,only for iOS
            YCQQ.ssoLogin(function(args){
                    alert(2222)
                     //alert(args.access_token);
                     //alert(args.userid);
                  },function(failReason){
                     alert("failed")
                     console.log(failReason);
            },checkClientIsInstalled);

    </script>
```

**Comment by iVanPan** [comment]
@fengfangqian  请问你有添加cordova.js嘛？cordova 插件要打包测试。

**Comment by stephenyaoshun** [comment]
有的,按照添加插件的方法编译了

**Comment by iVanPan** [comment]
@fengfangqian 在cordova build 以后在编译好的www文件夹中会有一个plugins文件夹check一下有没有一个名为org.zy.yuancheng.qq的文件夹，里面的ycqq.js在不在？同时check 编译完的config.xml里面有没有插件的定义。如果都没有问题的话，弄否劳烦截个图给我？

**Comment by stephenyaoshun** [comment]
@iVanPan 不好意思,图片怎么也传不上来,我在config.xml加了这个gap:plugin name="org.zy.yuancheng.qq" 以后还是不行ycqq.js也有

**Comment by iVanPan** [comment]
@fengfangqian ，外部的config.xml 是不用编辑的，我想知道的你的corodova 版本是多少？我刚刚去cordova 官网，看了一下,cordova  昨天发布了5.0的版本，插件方式有改变，所以在5.0的版本上面可能会有问题，这几天我会抽时间去适配cordova 5.0的版本。如果你是最新的5.0希望你耐心等待几日,如果你还是4.X的版本有问题的话，可以单独发邮件给我fan543119@gmail.com.

**Comment by stephenyaoshun** [comment]
@iVanPan 已经给你发邮件了

**Comment by iVanPan** [comment]
好的，晚些时候我会重新测试

—

**Comment by iVanPan** [comment]
@fengfangqian  你好，你的代码我看了一下，cordova插件调用要在deviceready事件以后才能调用，因为在deviceready之前插件还没有加载完全，所以会报错，说找不到对象，我重新用4.2版本的phonegap写了demo测试是没有问题的，希望你重新测试一下。
@cheft 你好，请问你的问题解决了吗？如果有任何bug希望可以得到你的回复，帮助我做的更好，谢谢。

**Comment by stephenyaoshun** [comment]
@iVanPan 非常感谢你热情的协助，问题已经解决成功分享到QQ，真是非常感谢你耐心的帮助，Thank you very much

**Comment by stephenyaoshun** [comment]
@iVanPan 请问怎么分享到qzone

**Comment by iVanPan** [comment]
@fengfangqian  你可以看我的js和java代码参照着来写，这是官方插件开发指导 https://cordova.apache.org/docs/en/edge/guide_hybrid_plugins_index.md.html#Plugin%20Development%20Guide

**Comment by stephenyaoshun** [comment]
@iVanPan 好的
