### ISSUE TITLE
Unexpected close tag

### ISSUE THREAD

**Issue by hcxiong** [iVanPan/Cordova_QQ#11]
不好意思，安装最新的时又出现了一个问题，请帮忙看看：
sudo cordova plugin add https://github.com/iVanPan/Cordova_QQ.git --variable QQ_APP_ID=******
Fetching plugin "https://github.com/iVanPan/Cordova_QQ.git" via git clone
Repository "https://github.com/iVanPan/Cordova_QQ.git" checked out to git ref "master".
Failed to fetch plugin https://github.com/iVanPan/Cordova_QQ.git via git.
Either there is a connection problems, or plugin spec is incorrect:
    Error: Unexpected close tag
Line: 65
Column: 15
Char: >

**Comment by hcxiong** [comment]
是这段代码引起的：

```
<!--allow non-HTTPS traffic -->
<config-file platform="ios" target="*-Info.plist" parent="NSAppTransportSecurity">
   <dict>
    <key>NSAllowsArbitraryLoads</key>
    </true>
  </dict>
</config-file>
```

**Comment by iVanPan** [comment]
嗯 已经修改好上传了

**Comment by iVanPan** [comment]
正在更新npm

**Comment by iVanPan** [comment]
@hcxiong  你重新安装测试一下 应该可以了！

**Comment by hcxiong** [comment]
嗯，谢谢
