### ISSUE TITLE
从qq客户端跳转回应用后没有返回值

### ISSUE THREAD

**Issue by xingwanying** [iVanPan/Cordova_QQ#12]
cordova 5.1.1
ios
var checkClientIsInstalled = 1;//default is 0,only for iOS
YCQQ.ssoLogin(function(args){
      alert(args.access_token);
      alert(args.userid);
      },function(failReason){
       console.log(failReason);
},checkClientIsInstalled);
function里面的代码都没有执行，得不到返回值，alert改为其他内容也并没有执行，求问

**Comment by iVanPan** [comment]
@xingwanying  您好，请问您的插件是哪个版本？是在iOS 9 上面运行吗？ 我用最新版本的插件在iOS 9 上面没有你说的问题。我测试的cordova 版本是5.3.3 cordova - ios 版本是3.9.1
