### ISSUE TITLE
QQ登录后再QQ退出，然后再QQ登录拉不起QQ授权登录页，显示为空白页

### ISSUE THREAD

**Issue by lianghuiyuan** [iVanPan/Cordova_QQ#14]
你好，我使用本插件的时候，出现：QQ登录后再QQ退出，然后再QQ登录拉不起QQ授权登录页，显示为空白页
我换用了你插件里面的**_example_www/**_测试了也是一样的问题。

```
测试环境:
 ios 9.1
 iphone6
 cordova 5.3.3
```

麻烦你确认一下是不是插件的问题，或者是ios 9兼容的问题？ 
因为我用iPhone4 ios8.4测试是没有问题的。

一下是重新QQ登录显示的空白页：

![215966ad276ce97f68090f6f4bf7c6a8](https://cloud.githubusercontent.com/assets/8090998/10873010/851ece1e-8148-11e5-9625-5516c8aa4632.png)

**Comment by iVanPan** [comment]
@lianghuiyuan  感谢反馈，最近腾讯官方SDK有更新，支持iOS9 的一些东东，这几天我会抽空更新一个插件版本

**Comment by lianghuiyuan** [comment]
@iVanPan 刚刚对比了一下ios8.4，确切的说是没有拉起这个页面：

http://xui.ptlogin2.qq.com/cgi-bin/xlogin?appid=[XXXXXXXX]&pt_3rd_aid=[XXXXXXXX]&style=35&s_url=http%3A%2F%2Fconnect.qq.com&refer_cgi=m_authorize&ucheck=1&fall_to_wv=1&response_type=token&sdkv=2.9&switch=1&state=test&client_id=[XXXXXXXX]&redirect_uri=auth%3A%2F%2Fwww.qq.com&status_machine=iPhone7%2C2&status_version=9&status_os=9.1&display=mobile&scope=get_user_info%2Cget_simple_userinfo%2Cadd_album%2Cadd_idol%2Cadd_one_blog%2Cadd_pic_t%2Cadd_share%2Cadd_topic%2Ccheck_page_fans%2Cdel_idol%2Cdel_t%2Cget_fanslist%2Cget_idollist%2Cget_info%2Cget_other_info%2Cget_repost_list%2Clist_album%2Cupload_pic%2Cget_vip_info%2Cget_vip_rich_info%2Cget_intimate_friends_weibo%2Cmatch_nick_tips_weibo&sdkp=i

辛苦了，期待早日更新。感谢！

**Comment by iVanPan** [comment]
@lianghuiyuan  新版本已经更新了, 支持iOS 9 biteCode, 页面没有拉起应该是白名单问题，已经解决，在我的iPhone上面测试通过了。你可以测试一下，有任何问题 欢迎反馈

**Comment by iVanPan** [comment]
@chengrenz 新版本已更新，app store 提交问题是腾讯SDK的问题，应该在新版本的SDK里面解决了，希望可以测试 反馈

**Comment by lianghuiyuan** [comment]
@iVanPan 更新了插件测试了一下，该问题已解决。非常感谢，辛苦了！
