### ISSUE TITLE
ReferenceError: YCQQ is not defined

### ISSUE THREAD

**Issue by liuxj1018** [iVanPan/Cordova_QQ#15]
我在controller中调用：
var checkClientIsInstalled = 1;
YCQQ.ssoLogin(function(args){
      alert(args.access_token);
      alert(args.userid);
      },function(failReason){
       console.log(failReason);
},checkClientIsInstalled);
在android手机上错误信息：ReferenceError: YCQQ is not defined。
咨询下是什么原因呢

**Comment by iVanPan** [comment]
在deviceready 以后才能调用插件

—

**Comment by liuxj1018** [comment]
已经deviceready 了，是执行完deviceready后加载登录页面后才执行的登录动作，调用的qq登录

**Comment by iVanPan** [comment]
@liuxj1018  跑demo 可以运行成功嘛？

**Comment by iVanPan** [comment]
@liuxj1018  出现这个问题 一般 是ycqq.js 加载没有成功

**Comment by iVanPan** [comment]
@liuxj1018  我重新在 Android 5.1.1 Cordova 5.3.3 上面做了测试，没有任何错误，请问你是在什么情况下面出现这种情况？

**Comment by liuxj1018** [comment]
找到原因了，ionic在deviceready前加载了router中的默认页面，该页面中调用了ycqq，导致没有加载成功。删除该页面加载，后面就可以。感谢您的答复。
