### ISSUE TITLE
编译OK，但是发布App Store时出错

### ISSUE THREAD

**Issue by ryanlin1986** [iVanPan/Cordova_QQ#17]
错误信息如下：

ERROR ITMS-90535:"Unexpected CFBundleExecutable Key. The bundle at Playload/myapp.app/TecentOpenApi_iOS_Bundle.bundle' does not contain a bundle executable.If the bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its infoplist and using a CFBundlePackageType of BNDL.

**Comment by iVanPan** [comment]
@ryanlin1986  是最新版本0.3.9 吗？ 你可以把腾讯的SDK的info.plist 删除就行了

**Comment by iVanPan** [comment]
@ryanlin1986  Xcode7 iOS 9 app store 的新要求 http://stackoverflow.com/questions/32622899/itms-90535-unable-to-publish-ios-app-with-latest-google-signin-sdk

**Comment by ryanlin1986** [comment]
Thanks, 是我的问题， config直接从0.3.8修改到0.3.9编译的，导致部分文件没有删除，更新插件一定要删除再重新添加。
