### ISSUE TITLE
貌似更新后有些问题，cordova更新到5.0也不行

### ISSUE THREAD

**Issue by stephenyaoshun** [iVanPan/Cordova_QQ#2]
fengfangqiandeMacBook-Pro:xqb-app fengfangqian$ cordova plugin add https://github.com/iVanPan/Cordova_QQ.git --variable QQ_APP_ID=1104567544
Fetching plugin "https://github.com/iVanPan/Cordova_QQ.git" via git clone
Installing "org.zy.yuancheng.qq" for android
Failed to install 'org.zy.yuancheng.qq':CordovaError: Plugin doesn't support this project's cordova-android version. cordova-android: 3.7.1, failed version requirement: >=4.0.0-dev
    at checkEngines (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:116:29)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:289:16
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
Plugin doesn't support this project's cordova-android version. cordova-android: 3.7.1, failed version requirement: >=4.0.0-dev
fengfangqiandeMacBook-Pro:xqb-app fengfangqian$ cordova -v
5.0.0

**Comment by iVanPan** [comment]
@fengfangqian  你的cordova更新了，但是android工程没有update 还是3.7.1的版本 这个插件由于cordova API改动 需要cordova-android 4.0 及以上的版本。请运行命令 cordova platform update android 更新你的cordova-android 版本

**Comment by stephenyaoshun** [comment]
@iVanPan 好的,不知道更新了Android版本会影响别的插件么

**Comment by iVanPan** [comment]
@fengfangqian  cordova android 4.0 修改了 从config.xml 读取preference配置项的接口，一旦插件要有自己的自定义preference都会收到影响。

**Comment by stephenyaoshun** [comment]
@iVanPan 那不悲剧了,我就有用到weibo和微信,你的qq插件之前的版本都是ok,后来我删了项目正式弄的时候从你这里添加插件的时候就不能用了,你还能给个以前的可用的版本给我吗,邮箱是fengfangqian@163.com

**Comment by iVanPan** [comment]
@fengfangqian  sorry，我所有插件都是自己写的，没有保留原来的代码。要适配最新的系统你早晚要更新。weibo你可以查看我的另外一个仓库，我也上传到github了。微信，我自己有写，就写了分享网页，到朋友圈，微信好友，还有三方登录，由于微信认证还没有下来，所以登录的代码还没有测试过，没有上传，如何要的话我可以发你一份
