### ISSUE TITLE
为什么分享到qq(YCQQ.shareToQQ) 给我弹出”cancelled by user“

### ISSUE THREAD

**Issue by zhangna0922** [iVanPan/Cordova_QQ#20]

**Comment by iVanPan** [comment]
@zhangna0922 你有取消分享嘛？取消分享就会有这个提示

**Comment by zhangna0922** [comment]
没有，我点击“分享” 就提示我“cancelled by user”,请问，我该怎么做？

**Comment by iVanPan** [comment]
我知道了，下了班晚上我会check的

—

**Comment by iVanPan** [comment]
@zhangna0922 你好 你demo 运行测试正确吗？我测试了一下没有问题哦！

**Comment by zhangna0922** [comment]
还不行，你可以把你的demo 发给我看看嘛？
$ionicActionSheet.show({
                buttons: [
                    { text: '分享至微信朋友圈' },
                    { text: '分享给微信好友' },
                    { text: '分享给QQ' },
                    { text: '分享给QQ空间' }
                ],
                titleText: '分享',
                cancelText: '取消',
                cancel: function() {
                    // 取消时执行
                },
                buttonClicked: function(index) {
                    
                    if(index == 2){//分享qq
                        var args = {};
                         args.url = url;
                         args.title = title;
                         args.description = goods.name;
                         args.imageUrl = [imageUrl];
                         args.appName = "cordova-qq";
                         YCQQ.shareToQQ(function () {
                         alert("share success");
                         }, function (failReason) {
                         alert(failReason);
                         }, args);
                    }

**Comment by iVanPan** [comment]
@zhangna0922  demo 就是项目里面example_www 啊

**Comment by zhangna0922** [comment]
ok，我试试你的demo

**Comment by hqingyi** [comment]
@zhangna0922 我们碰到的问题是由于传入参数格式不对导致的，比如url没有前缀http://导致～

见此PR: https://github.com/iVanPan/Cordova_QQ/pull/22
