### ISSUE TITLE
ios添加插件失败的

### ISSUE THREAD

**Issue by mjbin** [iVanPan/Cordova_QQ#21]
你好，我先是在window环境下添加了android平台，然后安装了插件。在windows环境下开发是经过了测试，正常的。后来我到mac环境下再添加ios平台，结果报错。提示Failed to install 'cordova-plugin-qqsdk':Error: Variable(s) missing: QQ_APP_ID;请问是什么情况？

**Comment by iVanPan** [comment]
要先删掉插件 重新安装，两个平台分开添加会有这个问题！重现安装一下就好了

—

**Comment by mjbin** [comment]
已经重新装上了，谢谢回复
