### ISSUE TITLE
为什么一定要android mini sdk 14呢？

### ISSUE THREAD

**Issue by flyshark** [iVanPan/Cordova_QQ#24]
可以兼容低版本吗？

**Comment by iVanPan** [comment]
我没有限制android sdk 版本 只限制了Cordova的版本。你看一下包了什么错 是什么要求最低版本的

—

**Comment by iVanPan** [comment]
@flyshark  能把错误给我看一下吗？

**Comment by flyshark** [comment]
执行cordova build命令，提示：
FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':processDebugManifest'.
  
  > Manifest merger failed : uses-sdk:minSdkVersion 8 cannot be smaller than versi
  > on 14 declared in library D:\APMServ5\www\platforms\android\build
  > \intermediates\exploded-aar\android\CordovaLib\unspecified\debug\AndroidManifest
  > .xml
  >     Suggestion: use tools:overrideLibrary="org.apache.cordova" to force usag
  > e
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

我把minSdk 从默认的14修改成8
AndroidManifest.xml
<uses-sdk android:minSdkVersion="8" android:targetSdkVersion="22" />

执行执行cordova build命令就报上面的错。。
分析了下，是cordova本身的问题，但是改成8之后，cordova build命令失败，但是eclipse里编译可以通过。

**Comment by iVanPan** [comment]
@flyshark  在cordova config.xml 文件中添加 [preference name="android-minSdkVersion" value="8" ]了吗？ 你是直接在Android Mainfest改的吗？ 不能直接改的
