### ISSUE TITLE
导入ionic项目不能build

### ISSUE THREAD

**Issue by David-Pan** [iVanPan/Cordova_QQ#29]
ionic build android 失败，不知道是否是jar包与我现有的jar包有冲突？
android-async-http-1.4.6.jar
android-support-v4.jar
happy-dns-0.2.4.jar
httpclient-4.3.6.jar
mta-sdk-1.6.2.jar
open_sdk_r5509.jar
qiniu-android-sdk-7.0.4.jar

**Comment by David-Pan** [comment]
Error:Execution failed for task ':dexDebug'.

> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>     D:\Android\android_sdk_20151022\android_sdk_20151022\build-tools\23.0.1\dx.bat --dex --no-optimize --output F:\hzy\platforms\android\build\intermediates\dex\debug --input-list=F:\hzy\platforms\android\build\intermediates\tmp\dex\debug\inputList.txt
> Error Code:
>     2
> Output:
>     UNEXPECTED TOP-LEVEL EXCEPTION:
>     com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
>         at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
>         at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
>         at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
>         at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
>         at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
>         at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
>         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
>         at com.android.dx.command.dexer.Main.run(Main.java:277)
>         at com.android.dx.command.dexer.Main.main(Main.java:245)
>         at com.android.dx.command.Main.main(Main.java:106)

**Comment by iVanPan** [comment]
把v4包删除试试

—

**Comment by David-Pan** [comment]
是的，删除后就没问题了。
