### ISSUE TITLE
ios8上登陆授权失败110404

### ISSUE THREAD

**Issue by stephenyaoshun** [iVanPan/Cordova_QQ#3]
@iVanPan 不好意思又打扰你，接入之后android是ok的，但是在ios上出现授权失败的问题，不知可否协助一下我

**Comment by iVanPan** [comment]
@fengfangqian  这个不是代码的问题，去open.qq.com 把你apple 平台的信息填完整就好了

**Comment by iVanPan** [comment]
@fengfangqian  错误码的原因看这里http://wiki.open.qq.com/wiki/mobile/API%E8%B0%83%E7%94%A8%E8%AF%B4%E6%98%8E#6._.E8.BF.94.E5.9B.9E.E7.A0.81.E8.AF.B4.E6.98.8E。      check一下你iOS里面URLTypes 有没有设置正确，cordova 是有一个URLTypes相关的BUG的 我在readme里面写了

**Comment by stephenyaoshun** [comment]
@iVanPan urltypes都有设置 我已经提交审核了，等审核过了再试试，谢谢了

**Comment by stephenyaoshun** [comment]
@iVanPan 又要麻烦你了，现在不报这个错误了，授权登录完成后立即返回了应用，没有到qq好友的分享界面去YCQQ.shareToQQ(function(){
            alert("分享成功");
            //console.log("share success");
        },function(failReason){
            alert("分享失败");
            //console.log(failReason);
        },args);
这个函数也会执行分享成功，请问这是什么情况？

**Comment by iVanPan** [comment]
@fengfangqian  这个我也不清楚，我只是写一个插件提供接口去调用而已。检查一下你的业务逻辑代码，可能是哪里触发调用了分享接口

**Comment by stephenyaoshun** [comment]
@iVanPan 我编译的时候看到有这样的错误，不知道是什么问题
In file included from /Users/fengfangqian/Desktop/xqb-app_debug/platforms/ios/小钱包/Plugins/org.zy.yuancheng.qq/YCQQ.m:2:
小钱包/Plugins/org.zy.yuancheng.qq/YCQQ.h:5:29: warning: cannot find protocol definition for 'TencentSessionDelegate'
@interface YCQQ : CDVPlugin<TencentSessionDelegate>
                            ^
In file included from /Users/fengfangqian/Desktop/xqb-app_debug/platforms/ios/小钱包/Plugins/org.zy.yuancheng.qq/YCQQ.m:2:
In file included from 小钱包/Plugins/org.zy.yuancheng.qq/YCQQ.h:4:
小钱包/Plugins/org.zy.yuancheng.qq/TencentOpenAPI.framework/Headers/TencentOAuth.h:15:11: note: protocol 'TencentApiInterfaceDelegate' has no definition
@protocol TencentApiInterfaceDelegate;
          ^
1 warning generated.

**Comment by iVanPan** [comment]
@fengfangqian ,这个不是错误，是warning。SDK的问题，在申明协议的时候提示：cannot find protocol declaration for  "xxDelegate"， 就表示你在两个类中，交叉应用了彼此。可以看一下stackoverflow http://stackoverflow.com/questions/6447573/cannot-find-protocol-declaration?lq=1    上面的回答，而且下面的warning是发生在TencentOpenAPI.framework内部，即QQ SDK里面，你可以去看一下QQ官方SDK Demo 也有这个问题的
