### ISSUE TITLE
ReferenceError: YCQQ is not defined

### ISSUE THREAD

**Issue by garyganyang** [iVanPan/Cordova_QQ#30]
.controller('aaaCtrl', function ($rootScope, $scope) {
    $scope.loginByQQ =function(){
      var checkClientIsInstalled = 1;//default is 0,only for iOS
      YCQQ.ssoLogin(function(args){
        alert(args.access_token);
        alert(args.userid);
      },function(failReason){
        console.log(failReason);
      },checkClientIsInstalled);
    }
  })

< button ng-click="loginByQQ ()" >login< / button>

device已经ready了,再点击按钮登录, 报错 YCQQ is not defined, 我该怎么检查哪儿会有问题呢? 非常感谢

**Comment by iVanPan** [comment]
@garyganyang  Demo 运行正确吗？ 是真机运行吗？

**Comment by garyganyang** [comment]
@iVanPan Demo运行正常,  是真机运行, 我是用的ionic

**Comment by iVanPan** [comment]
@garyganyang  那就很有可能是你业务逻辑代码的问题了，以前也有人遇到这个问题，最后是controller还是没有在deviceReady的时候调用，仔细检查一下看看，你这样我也看不出问题的

**Comment by garyganyang** [comment]
感谢 感谢, 问题找到了 是因为没有  添加 < script src="cordova.js">< / script>
