### ISSUE TITLE
iOS分享出现闪退，闪退之前提示分享成功

### ISSUE THREAD

**Issue by Voyager-sun** [iVanPan/Cordova_QQ#31]
Xcode最后提示：THREAD WARNING: ['YCQQ'] took '240344.467041' ms. Plugin should use a background thread.

**Comment by iVanPan** [comment]
@Voyager-sun  Demo 运行也会闪退吗？ 真机吗？ Xcode和iOS版本多少？

**Comment by Voyager-sun** [comment]
我用的是phonegap、ionic，xcode 7.2.1.是真机。ios6

**Comment by Voyager-sun** [comment]
真机，我使用的是phonegap，ionic。xcode是7。2.1.ios版本是6

**Comment by Voyager-sun** [comment]
使用demo也会，可能是版本太低，我先试试高版本

**Comment by Voyager-sun** [comment]
@iVanPan 谢谢，现在可以了
