### ISSUE TITLE
token过期时间，如何获取呢?

### ISSUE THREAD

**Issue by flyshark** [iVanPan/Cordova_QQ#32]
token过期时间，如何获取呢?

**Comment by iVanPan** [comment]
@flyshark 请问你拿过期时间是用来干什么的？这个版本我并没有封装过期时间，如果有必要的话 我会在下个版本中加入

**Comment by flyshark** [comment]
获取到token以后，我们打算把token和过期时间（默认是3个月）先存在本地，下次自动登录的时候，会先本地判断这个token是否过期，省得每次都去QQ那边验证token是否有效，如果过期，就到QQ那边获取新的token。
当然我们也可以自己自定义一个token时间，比如2个月，但是如果2个月之后，我们本地判断token过期，就会去QQ那边验证，但是QQ返回时未过期是有效的，就会有点小问题。
只是觉得同QQ的服务器保持一致是否更好一点？

**Comment by iVanPan** [comment]
@flyshark  新版本已经可以获取expires_time

**Comment by flyshark** [comment]
好的，谢谢.

2016-06-06 16:27 GMT+08:00 Van notifications@github.com:
