### ISSUE TITLE
请问,提示分享校验失败是什么原因?

### ISSUE THREAD

**Issue by TimWu0101** [iVanPan/Cordova_QQ#35]

**Comment by iVanPan** [comment]
@mexx880101  能告诉我你是Android 还是iOS 系统版本是什么？cordova版本是多少 有没有错误log？

**Comment by TimWu0101** [comment]
安卓系统, cordova 6.1.1 安卓5.0
没有错误,点击出发分享事件可以跳转QQ好友页面,但是选择完好友之后点确定就提示分享校验失败

**Comment by iVanPan** [comment]
@mexx880101 签名正确吗？

**Comment by mexx880101** [comment]
qqappid?
