### ISSUE TITLE
调用出错

### ISSUE THREAD

**Issue by zhudoupi** [iVanPan/Cordova_QQ#39]
兄弟，该应用登录功能版本较旧，无法使用qq帐号登录，请升级到最新版本，

辛苦了 ，能抽时间更新一下吗

**Comment by iVanPan** [comment]
@zhudoupi  已经是最新的SDK了，劳烦开issue前认真看一下文档好吗？ 你的开发环境、log，插件版本什么说明都没有，这样的issue对大家没有任何帮助的。

**Comment by zhudoupi** [comment]
我用的是你的demo运行的 ，调用后弹出这个页面  这是qq页面弹出的，failReason 返回的是“cancelled by user”
安卓手机 4.4
cordova 6.1.1    

手机qq是最新版本
![Uploading 1.jpg…]()

**Comment by zhudoupi** [comment]
照片不知道为什么传不上来，就是条转到qq授权那个页面，正在获取 授权信息，然后弹出一个框 登陆失败：该应用的登陆功能版本交就，无法使用qq账号登陆，请升级到最新版本，如果还无法解决，请联系开发者，（错误码：100044）
