### ISSUE TITLE
可以加上获取好友关系吗？

### ISSUE THREAD

**Issue by Poordeveloper** [iVanPan/Cordova_QQ#4]
很感谢你的工作。

**Comment by iVanPan** [comment]
@Poordeveloper  ，你好，获取好友关系？是拿用户的好友有哪些吗？还是其他？我在QQ 开放平台的API使用说明上面 并没有找到这个API。有的话，还麻烦你指点一下。

**Comment by Poordeveloper** [comment]
就是
http://wiki.open.qq.com/wiki/QQ%E7%94%A8%E6%88%B7%E8%83%BD%E5%8A%9B#3.2_.E9.82.80.E8.AF.B7.E5.A5.BD.E5.8F.8B
中的
“QQ关系链”

**Comment by iVanPan** [comment]
QQ关系链里面有很多功能。是3.1的用户头像设置 还是全部？

On Thursday, Jun 11, 2015 at 23:25, carriez notifications@github.com, wrote:

就是
http://wiki.open.qq.com/wiki/QQ%E7%94%A8%E6%88%B7%E8%83%BD%E5%8A%9B#3.2_.E9.82.80.E8.AF.B7.E5.A5.BD.E5.8F.8B

中的

“QQ关系链”

**Comment by Poordeveloper** [comment]
我觉得是跟“邀请”相关的功能。

**Comment by iVanPan** [comment]
@Poordeveloper  你好，你说的邀请是邀请好友功能吧，我看了一下API 目前只有Android平台支持邀请好友，而且腾讯对邀请接口做了以下声明：**特别声明：**该接口目前仅支持白名单应用。出于信息安全的考虑，本接口目前升级中。升级完成前暂不接受开发者的授权申请。升级完成后，所有接入QQ登录的开发者将均可调用。如果你的目标平台不是Android，应用也没有获取到这个接口的权限，这个功能不会再短期内加上。[这里](http://wiki.open.qq.com/index.php?title=Android_API%E8%B0%83%E7%94%A8%E8%AF%B4%E6%98%8E&=45038#1.3_.E9.82.80.E8.AF.B7.E5.A5.BD.E5.8F.8B)是腾讯 SDK android API调用说明

**Comment by Poordeveloper** [comment]
好的，谢谢
