### ISSUE TITLE
QQ的两个AppId

### ISSUE THREAD

**Issue by furuihe** [iVanPan/Cordova_QQ#41]
QQ的appId分为android和ios两个，怎么同时进行设置呢？

**Comment by iVanPan** [comment]
@furuihe  自己直接在xcode或是Android Studio 里面进行修改，该其中一个，或是创建两个不同的Cordova 工程

**Comment by iVanPan** [comment]
@furuihe  在android 和iOS 的工程文件夹下面分别有个android.json 和ios.json 里面存储了插件的配置，你可以尝试修改这个json文件来实现

**Comment by furuihe** [comment]
@iVanPan 好的，感谢
