### ISSUE TITLE
发起权限请求

### ISSUE THREAD

**Issue by 312977** [iVanPan/Cordova_QQ#42]
当调用 window.YCQQ.ssoLogin 的时候 发起了 权限 读取app列表的请求，但是我点了允许之后，返回cancel by user  ,但是立马又进入到qq登录界面了  ,然后qq登录那个界面 显示了两遍，我点了一下登录 他显示正在拉去授权信息，然后这个界面闪了一下  还要继续点登录才能返回去

华为 p9 6.0  cordova 6.1.1

**Comment by iVanPan** [comment]
@312977  您好，感谢反馈，我在一加3的6.0.1系统上面并没有这个问题，如果你有更多信息可以提供的话，希望可以提供一下，谢谢
