### ISSUE TITLE
qq登录问题

### ISSUE THREAD

**Issue by giantss** [iVanPan/Cordova_QQ#45]
YCQQ.ssoLogin qq登录为什么就第一次授权的时候才会调用一次授权页面，退出在qq授权登录或者切换qq帐号后授权界面不会再次显示出来

**Comment by giantss** [comment]
。。。。 求解答啊 @iVanPan

**Comment by iVanPan** [comment]
@giantss  调用一下logout 方法试试

**Comment by giantss** [comment]
你是说每次授权完了要掉用logout吗

**Comment by iVanPan** [comment]
@giantss  没明白你的意思？ 你是要每次登陆都要授权？拿不到token吗？

**Comment by giantss** [comment]
额，难道不是每次都要调用授权的方法获取token吗？

**Comment by iVanPan** [comment]
@giantss  token 都是有有效期，一般都是一个月，接口里面会返回过期时间的，时间还没有到，你可以一直用原来的token。

**Comment by giantss** [comment]
哦，用原来的key是不是就不用微信授权界面了

**Comment by iVanPan** [comment]
@giantss  抱歉，没有明白你的意思

**Comment by giantss** [comment]
抱歉，我少打了字，用原来的key是不是就不用唤出微信授权界面了

**Comment by iVanPan** [comment]
@giantss  这个和微信有什么关系？ 拿到token 后保存下来 每次比对过期时间，还在有效期内就直接调用API，无效了就调用YCQQ.ssoLogin 重新授权，拿新的token。我觉得你可能没有弄明白token是干什么用的

**Comment by giantss** [comment]
好的 明白了 谢谢

**Comment by giantss** [comment]
token 和过期时间 是存客户端还是服务端呢
