### ISSUE TITLE
iOS 不能编译

### ISSUE THREAD

**Issue by ctl1690** [iVanPan/Cordova_QQ#46]
cordova 6.2
cordova ios@~4.1.1

The following build commands failed:
    Ld build/emulator/xxx.app/xxx normal i386
    GenerateDSYMFile build/emulator/xxxapp.dSYM build/emulator/xxx.app/xxx
(2 failures)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/xxx/Documents/Cordova6/xxx/platforms/ios/cordova/build-debug.xcconfig,-project,xxx.xcodeproj,ARCHS=i386,-target,xxx,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/xxx/Documents/Cordova6/xxx/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/xxx/Documents/Cordova6/xxx/platforms/ios/build/sharedpch

**Comment by iVanPan** [comment]
https://github.com/iVanPan/Cordova_QQ/issues/40
