### ISSUE TITLE
没有安装QQ客户端时，点击登录没反应，如何才能调出网页授权登录页面？

### ISSUE THREAD

**Issue by efon6653** [iVanPan/Cordova_QQ#47]
有安装QQ客户端时可能正常使用。没有安装QQ客户端时，点击登录没反应，没安装QQ客户端时如何才能调出网页授权登录页面？

**Comment by iVanPan** [comment]
@efon6653  这个你要问一下腾讯那边了，我在iOS 模拟器里面可以出现网页授权，其他都不行，貌似和腾讯的策略有关系
