### ISSUE TITLE
腾讯QQ提醒，版本需要升级

### ISSUE THREAD

**Issue by johnnynode** [iVanPan/Cordova_QQ#51]
应用提示信息 ： 该应用登录功能版本较旧，无法使用QQ账号登录，请升级到最新版本。如果还无法解决，请联系开发者升级，错误代码：100044

**Comment by iVanPan** [comment]
@johnnynode  你的是Android的吧？文档上面写着100044是签名不正确，麻烦开issue之前认真看一下issue模版，提供一些完整的信息，这个很重要，举手之劳而已不是吗？

**Comment by johnnynode** [comment]
可以使用，安卓正常，返回三个字段，签名是正确的，打包时候用的时你的example,所以返回的错误代码。可以close了，为你这个插件点个赞！
