### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by iyibo** [iVanPan/Cordova_QQ#52]
你好  ios上成功调用了插件，但是Android 上却build失败了，我用的是Android studio，
报错内容如下：
- What went wrong:
  A problem occurred configuring root project 'android'.
  > Could not resolve all dependencies for configuration ':_debugCompile'.
  > Could not find any version that matches com.android.support:support-v4:23.3                   .0+.
   Searched in the following locations:
       https://repo1.maven.org/maven2/com/android/support/support-v4/maven-met                   adata.xml
       https://repo1.maven.org/maven2/com/android/support/support-v4/
       file:/C:/sdk/extras/android/m2repository/ceom/android/support/support-v4                   /maven-metadata.xml
       file:/C:/sdk/extras/google/m2repository/com/android/support/support-v4/                   maven-metadata.xml
       file:/C:/sdk/extras/google/m2repository/com/android/support/support-v4/
   Required by:
       :android:unspecified

我检查了sdk manager  是没问题的

**Comment by iVanPan** [comment]
com.android.support:support-v4:23.3 找不到的缘故
