### ISSUE TITLE
QQ好友分享，回调问题

### ISSUE THREAD

**Issue by zwwhappy** [iVanPan/Cordova_QQ#53]
QQ好友分享，跳转到QQ应用后，马上就触发了回调

**Comment by iVanPan** [comment]
@zwwhappy  是iOS端吗？ iOS端有这个问题，我刚刚发了一个 0.4.1的版本，应该修复了，你可以试一下

**Comment by zwwhappy** [comment]
是的，看了新版本，解决了，good
