### ISSUE TITLE
cordova-plugin-qqsdk 0.4.0 "YCQQ" cordova 6.3.1 编译报错：

### ISSUE THREAD

**Issue by chrisyuyangshen** [iVanPan/Cordova_QQ#55]
Before submitting issues ...
- 确保你的 App 在[腾讯开放平台](http://open.qq.com/)已审核通过.
- 如果是 Android 平台请确保你的apk签名是正确的.
- 请确认demo已测试通过.
- 请先搜索相关的issues,看是否同样的问题已经有解决方案了.
- 发生出现错误码的情况，请前去腾讯开放平台咨询.

当你提交 issues 的时候, 请提供以下信息来帮助开发者更好的修复Bug:
- 开发环境: 插件版本, Cordova版本, Xcode版本.
- 如果出现错误，希望提供Xcode或Android Studio的错误日志.
- 如果有其他额外的信息，也希望可以提供一下，帮助我们更快的定位问题.

**Comment by chrisyuyangshen** [comment]
warning: ignoring file choome/Plugins/cordova-plugin-qqsdk/TencentOpenAPI.framework/TencentOpenAPI, missing required architecture i386 in file choome/Plugins/cordova-plugin-qqsdk/TencentOpenAPI.framework/TencentOpenAPI (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_QQApiInterface", referenced from:
      objc-class-ref in YCQQ.o
  "_OBJC_CLASS_$_QQApiNewsObject", referenced from:
      objc-class-ref in YCQQ.o
  "_OBJC_CLASS_$_SendMessageToQQReq", referenced from:
      objc-class-ref in YCQQ.o
  "_OBJC_CLASS_$_TencentOAuth", referenced from:
      objc-class-ref in YCQQ.o
  "_kOPEN_PERMISSION_ADD_ALBUM", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_ADD_ONE_BLOG", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_ADD_SHARE", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_ADD_TOPIC", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_CHECK_PAGE_FANS", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_OTHER_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_SIMPLE_USER_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_USER_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_VIP_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_VIP_RICH_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_LIST_ALBUM", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_UPLOAD_PIC", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
ld: symbol(s) not found for architecture i386

**Comment by iVanPan** [comment]
cordova build --device
