### ISSUE TITLE
编译时出现问题

### ISSUE THREAD

**Issue by zlcfix** [iVanPan/Cordova_QQ#56]
ios编译时报错，我xcode里相关工程文件和framework文件都导进去了，报错如下：

Plugins/cordova-plugin-qqsdk/TencentOpenAPI.framework/TencentOpenAPI (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_QQApiInterface", referenced from:
      objc-class-ref in YCQQ.o
  "_OBJC_CLASS_$_QQApiNewsObject", referenced from:
      objc-class-ref in YCQQ.o
  "_OBJC_CLASS_$_SendMessageToQQReq", referenced from:
      objc-class-ref in YCQQ.o
  "_OBJC_CLASS_$_TencentOAuth", referenced from:
      objc-class-ref in YCQQ.o
  "_kOPEN_PERMISSION_ADD_ALBUM", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_ADD_ONE_BLOG", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_ADD_SHARE", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_ADD_TOPIC", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_CHECK_PAGE_FANS", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_OTHER_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_SIMPLE_USER_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_USER_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_VIP_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_VIP_RICH_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_LIST_ALBUM", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_UPLOAD_PIC", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by iVanPan** [comment]
@zlcfix  看文档，cordova build --device

**Comment by xinyi1989** [comment]
@zlcfix  cordova build --device 编译通过后，生成了ipa文件，怎么安装到手机上测试呢？我的为什么安装不上呢
