### ISSUE TITLE
TencentOpenAPI.framework/TencentOpenAPI, missing required architecture i386 

### ISSUE THREAD

**Issue by liangxp** [iVanPan/Cordova_QQ#57]
- 开发环境: Cordova6.3.1
- cordova build ios编译错误信息
`ld: warning: ignoring file 亿信天合/Plugins/cordova-plugin-qqsdk/TencentOpenAPI.framework/TencentOpenAPI, missing required architecture i386 in file 亿信天合/Plugins/cordova-plugin-qqsdk/TencentOpenAPI.framework/TencentOpenAPI (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_QQApiInterface", referenced from:
      objc-class-ref in YCQQ.o
  "_OBJC_CLASS_$_QQApiNewsObject", referenced from:
      objc-class-ref in YCQQ.o
  "_OBJC_CLASS_$_SendMessageToQQReq", referenced from:
      objc-class-ref in YCQQ.o
  "_OBJC_CLASS_$_TencentOAuth", referenced from:
      objc-class-ref in YCQQ.o
  "_kOPEN_PERMISSION_ADD_ALBUM", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_ADD_ONE_BLOG", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_ADD_SHARE", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_ADD_TOPIC", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_CHECK_PAGE_FANS", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_OTHER_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_SIMPLE_USER_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_USER_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_VIP_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_GET_VIP_RICH_INFO", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_LIST_ALBUM", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
  "_kOPEN_PERMISSION_UPLOAD_PIC", referenced from:
      -[YCQQ qqLogin:] in YCQQ.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/亿信天合.app/亿信天合 normal i386

(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/junweiren/H5Apps/Iyxth/platforms/ios/cordova/build-debug.xcconfig,-project,亿信天合.xcodeproj,-target,亿信天合,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,build,CONFIGURATION_BUILD_DIR=/Users/junweiren/H5Apps/Iyxth/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/junweiren/H5Apps/Iyxth/platforms/ios/build/sharedpch`

**Comment by iVanPan** [comment]
cordova build --device
