### ISSUE TITLE
Could not find any matches for com.android.support:support-v4:23.3.0+ as no versions of com.android.support:support-v4 are available.

### ISSUE THREAD

**Issue by liangxp** [iVanPan/Cordova_QQ#58]
- 开发环境:  cordova6.3.1
`BUILD FAILED

Total time: 1 mins 55.378 secs
Error: /Users/junweiren/H5Apps/Iyxth/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any matches for com.android.support:support-v4:23.3.0+ as no versions of com.android.support:support-v4 are available.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
         https://jcenter.bintray.com/com/android/support/support-v4/maven-metadata.xml
         https://jcenter.bintray.com/com/android/support/support-v4/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output`
发现在原有项目中project.properties加入了如下代码导致：
cordova.system.library.1=com.android.support:support-v4:23.3.0+
请问是本项目需要引入特殊版本的jar么？

**Comment by iVanPan** [comment]
android sdk 自己下载一下 找不到这个包而已，Google一下就有了，close的issue里面都有提到
