### ISSUE TITLE
iOS平台：取消分享，YCQQ.shareToQQ返回success

### ISSUE THREAD

**Issue by woshibt** [iVanPan/Cordova_QQ#59]
弹出QQ分享界面时不分享而点击iPhone状态栏上的“返回xxxAPP”链接，YCQQ.shareToQQ返回success。

**Comment by iVanPan** [comment]
@woshibt  我测试了一下 我这边并没有这个问题，无法重现哎。

**Comment by iVanPan** [comment]
@woshibt  你可能用的是上一个版本，尝试使用最新的版本，应该没有这个问题

**Comment by woshibt** [comment]
@iVanPan 能否分享一下你的调用代码？也许是我的代码的问题？

**Comment by iVanPan** [comment]
@woshibt  就是仓库里面的demo啊，有个exmaple_www文件夹的
