### ISSUE TITLE
安装上了，但是用不了

### ISSUE THREAD

**Issue by junmin** [iVanPan/Cordova_QQ#6]
也测试了example www，里面的按钮都没有反应，是什么回事啊？

**Comment by junmin** [comment]
Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.8.10
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.6.1
Ionic App Lib Version: 0.3.3
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.10.38
Xcode version: Xcode 6.4 Build version 6E35b

**Comment by iVanPan** [comment]
@junmin，感谢反馈，请问你的cordova android 和Cordova iOS的版本是多少？晚上的时候我会重新测试排查这个问题。

—

**Comment by iVanPan** [comment]
如果是android的话，请确保签名是正确的

—

**Comment by junmin** [comment]
@iVanPan 你知道ionic-view吗？应该是ionic-view的问题。我一直用这个来调试app,  但是刚才我实机测试一下，example www是没有问题的。谢谢你这么快的反馈！如果有问题我再找你。谢谢。

**Comment by iVanPan** [comment]
@junmin 恩，欢迎交流。

—
