### ISSUE TITLE
iphone 4s  不能使用 ，在Xcode 中编译报错 ，5 6 7 没事

### ISSUE THREAD

**Issue by fengsong97** [iVanPan/Cordova_QQ#62]
请问怎么解决？
![image](https://cloud.githubusercontent.com/assets/12808002/21042171/ccb36cd8-be2a-11e6-82ea-cab177d0bee8.png)

**Comment by iVanPan** [comment]
@fengsong97 最新版本的SDK 已经不支持i386的架构了，你可以找个旧版本的SDK替换一下

**Comment by fengsong97** [comment]
去QQ开放平台找吗 ？ 我用之前的 （保存的你的插件里的sdk）  替换的话 ，是替换哪一个文件？

**Comment by fengsong97** [comment]
@iVanPan

**Comment by iVanPan** [comment]
@fengsong97  替换framework 就好了
