### ISSUE TITLE
希望增加 QQ_APP_ID 可以分平台设置

### ISSUE THREAD

**Issue by rehiy** [iVanPan/Cordova_QQ#65]
目前的参数如下
--variable QQ_APP_ID=YOUR_QQ_APPID

鉴于QQ的应用分发平台，给的key是区分ios和android的，需要分别设置2个key，每次编译都需要修改。
是否可以提供2个参数 
 Q_APP_ID_ANDROID  和 QQ_APP_ID

**Comment by iVanPan** [comment]
@anrip  
- Cordova 本身就是用来做跨平台的，我希望尽可能的统一，再加上--variable QQ_APP_ID=YOUR_QQ_APPID 这种方式本身就不是特别的友好，所以还没有很好的方案之前不会区分平台。      

- 在 Cordova 的 platform iOS Android 文件夹里面分别有一个 ios.json 和 android.json 文件， Cordova每次在build的时候都拿那里面的信息合成新的config.xml 和AndroidManifest，因此你每次build完以后会发现AndroidManifest 以及 config.xml 都变成了原来的样子。

- 你只要安装完插件，修改其中一个json文件中的config_munge节点下面的appid，下次编译就不用修改了，比如你使用iOS平台的QQ_APP_ID来安装插件，然后在 platform/android/android.json  文件中的APP_ID 替换为 android平台的即可
