### ISSUE TITLE
我想引用项目本身资源图片进行分享,绝对路径怎样写才正确?

### ISSUE THREAD

**Issue by sunyxq** [iVanPan/Cordova_QQ#67]
`file:///android_asset/www/assets/icon/favicon.ico`或
`assets/icon/favicon.ico`返回信息都是是"非法图片路径"

**Comment by iVanPan** [comment]
@sunyxq  目前对asset里面的图片还不支持，在后面几个版本会加入，你可以暂时转化成base64来调用
