### ISSUE TITLE
ios下qq不能直接唤出，非得下拉一次通知栏

### ISSUE THREAD

**Issue by whlhl2010** [iVanPan/Cordova_QQ#68]
xcode8，在ios10出现一个问题：比如分享，QQ不能直接唤出，非得下拉一次通知栏，才能唤出微信。不知你这边有没有碰到过这种情况？

**Comment by whlhl2010** [comment]
2017-03-12 17:56:45.294897 tcp[56048:11465860] THREAD WARNING: ['QQSDK'] took '2539.960938' ms. Plugin should use a background thread.
2017-03-12 17:56:45.492118 tcp[56048:11470060] PBItemCollectionServicer connection disconnected.

**Comment by iVanPan** [comment]
这个log没有关系的，一个是插件耗时希望使用后台异步线程，但是QQ sdk要求使用主线程，另外一个貌似也和sdk有关，不受影响，你新建一个工程用插件提供的demo试试分享能不能唤起QQ，我现在不在电脑边，晚上也会测试一下.

**Comment by whlhl2010** [comment]
@iVanPan 谢谢，我先试试，也麻烦你帮忙看看，我用你写的qq和微博分享都是同样的问题，下拉一下通知栏，就可以打开qq或者微博，然后分享和返回都是正常的

**Comment by iVanPan** [comment]
@whlhl2010 我用 Cordova 6.5.0，Cordova-iOS 4.3.1，在iPhone 6 Plus iOS 10.2.1 上面测试了一下并没有问题，你检查一下Xcode里面 URLTypes 和 LSApplicationQueriesSchemes 是否正确。你自己新建工程测试可以吗？ 还是说装了什么其他的插件发生了冲突？ 还有用其他 App 调用 QQ 分享是否正常？

**Comment by whlhl2010** [comment]
@iVanPan 非常感谢了，我也新建工程测试了，发现新增的工程用你提供的例子是可以的，装了挺多的插件的不确定是否冲突了，还有我发现我的工程里deviceready事件不像例子里那样一启动就执行 （我现在是用qq、微信、微博分享3个插件都是这个问题）

**Comment by iVanPan** [comment]
@whlhl2010 deviceready相关的问题倒不是了解的很多，在Cordova里面有一个“deviceready has not fired after 5 seconds.”的问题倒是知道，你可以尝试将插件和平台都更新到最新的版本，尤其是官方的一些插件，看能不能解决你现在的问题。

**Comment by whlhl2010** [comment]
@iVanPan 还要请教一下这个问题会不会和AngularJS有关系呢，有人问过吗？

**Comment by iVanPan** [comment]
@whlhl2010  没有 很多人都是用ionic的用的都是Angular

**Comment by iVanPan** [comment]
是最新版本的插件吗？分享不能唤起QQ？demo测试可以吗？

2017年3月12日 +0800 17:42 whlhl2010 <notifications@github.com>，写道：
