### ISSUE TITLE
能否加上getUserInfo接口？

### ISSUE THREAD

**Issue by Poordeveloper** [iVanPan/Cordova_QQ#7]
谢谢

**Comment by junmin** [comment]
@Poordeveloper  不需要的啊~ 直接GET一下下面REST接口，看看QQ的开发文档~

```
var url = "https://graph.qq.com/user/get_user_info?access_token=" + params.accessToken + "&oauth_consumer_key=APPID&openid=" + params.userId;
http.get(url)
```

**Comment by iVanPan** [comment]
@Poordeveloper  建议使用 @junmin 推荐的方法，虽然SDK也可以获取用户信息，但是我记得cordova 从本地代码层传数据到JS层是有限制的,超过1024部分会被截断。一般获取用户信息的JSON数据都是比较长的，而且直接在JS层用GET的方式更加方便。以上是我的个人看法，有什么想法欢迎交流探讨

**Comment by Poordeveloper** [comment]
好的，非常谢谢。
