### ISSUE TITLE
安卓权限问题

### ISSUE THREAD

**Issue by chenkun24** [iVanPan/Cordova_QQ#71]
为什么安卓的 WRITE_EXTERNAL_STORAGE 权限限定到 API22？

**Comment by iVanPan** [comment]
QQ SDK 本身不需要 WRITE_EXTERNAL_STORAGE 这个权限，由于我自己要处理图片所以加了这个权限，我查询了一下在 Android 4.4 的时候这个权限发生了变动，在应用程序的包文件夹内进行读写操作不再需要这个权限，但是我在 Android 5.0 上面测试发现有问题所以限定了 22，如果不限定在 Android 6.0 上面由于 Runtime Permissions 可能会造成一些问题，所以才有了这个限定。如果你有更好的方案也欢迎探讨
@chenkun24

**Comment by chenkun24** [comment]
现在有一个问题，就是用phonegap增加插件之后，这个权限会和默认的权限产生两条相同的权限，差别就是一条有maxsdkversion，一条没有，从而导致编译失败。这个问题有解决方案吗？

**Comment by iVanPan** [comment]
在 Cordova/Android 文件夹下面有个 andorid.json 文件，里面储存这所有插件的配置，每次 build 的时候会根据 android.json 里面的内容重现生成新的 Androidmanifest 文件，修改里面的内容把这个插件的 SD 卡 权限删掉就好了

**Comment by chenkun24** [comment]
这样的话，整个安卓文件夹都得提交，而且无法直接从config.xml生成一个完整的安卓项目？（即还要再次修改android文件夹里的文件）

**Comment by iVanPan** [comment]
@chenkun24  你自己修改试一下就知道了
