### ISSUE TITLE
新版本默认对url转义

### ISSUE THREAD

**Issue by puny-d** [iVanPan/Cordova_QQ#72]
你好，我发现新版本qq分享消息时，会对url进行转义，我是SPA单页面应用，url中会含有：#!作为分隔符，#被转义成了%23.。。。结果网页访问的时候，就会出现404。

我觉得应该把encodeUri的操作交给我们这些插件使用者比较好

**Comment by iVanPan** [comment]
@puny-d  Android 还是 iOS ？ 我对 URL 没有做什么特殊处理， 只是拿出来传递给 SDK 而已

**Comment by puny-d** [comment]
你好，我测试过了，只有在ios版本才出现，我看了你的源代码，我猜测可能问题出在：CDVQQSDK.m，这个文件          
`line323: NSURL *url = [NSURL URLWithString:[[shareData objectForKey:@"url"]stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]];
`
这一行代码，我对Objective-C不熟悉，stringByAddingPercentEscapesUsingEncoding，应该就是这个导致的吧。。。仅仅是猜测

**Comment by iVanPan** [comment]
@puny-d  好的，非常感谢，已经修复了
