### ISSUE TITLE
连续登录问题

### ISSUE THREAD

**Issue by chenkun24** [iVanPan/Cordova_QQ#73]
第一次从sso授权获取到token，但不登录，再次从sso授权时无法正常回调。

**Comment by iVanPan** [comment]
@chenkun24  iOS吧？ 测试了一下是有这个问题，已经改掉了，待会儿发个版本

**Comment by chenkun24** [comment]
是的👍👍

**Comment by chenkun24** [comment]
这样其实还有另一个问题，就是这种情况下没办法重新用另一个QQ登录，用的始终是第一次登录的QQ的授权信息。

**Comment by iVanPan** [comment]
@chenkun24  先要调用登出接口，或者是 去把原生代码里面的获取缓存token的代码删除

**Comment by chenkun24** [comment]
但是退出接口有个问题，我无法判断目前是否已经登录。如果目前已经登录没问题，如果目前没登录，调用logout则无回调消息。

**Comment by iVanPan** [comment]
@chenkun24  你是需要在登出的回调里面 做一些事情罗？不行我会考虑去掉那段逻辑

**Comment by chenkun24** [comment]
QQSDK.logout(successCallback, errorCallback)，如果当前未登录，调用这个接口，successCallback不会被调用。

**Comment by iVanPan** [comment]
@chenkun24  这个我明白，我还是去掉获取缓存token那段逻辑好了，发个 0.9.1 的版本给你

**Comment by chenkun24** [comment]
😂 因为微博sdk好像没这个问题，即使多次调用logout也没问题。楼主辛苦了🐳

**Comment by iVanPan** [comment]
@chenkun24  好了 你试一下

**Comment by chenkun24** [comment]
附带问另一个问题：args.client = QQSDK.ClientType.QQ; 这个args现在是必须的吗？

**Comment by iVanPan** [comment]
@chenkun24  我做了兼容 不写应该没有关系，默认是 QQ 只针对 iOS。主要是最新版本的SDK做出了改动，需要指定 QQ，或是 TIM，建议不要使用 TIM，试了一下发现目前 SDK 对TIM客户端还有问题

**Comment by chenkun24** [comment]
明白👍
