### ISSUE TITLE
Duplicate uses-permission element for Android

### ISSUE THREAD

**Issue by mackwan84** [iVanPan/Cordova_QQ#74]
Hey there, due to this commit my android build fails due to a duplicate <uses-permission>.

When I install the file-transfer plugin it adds this line to my AndroidManifest.xml.
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

When I install the your plugin it adds this line to my AndroidManifest.xml file.
<uses-permission android:maxSdkVersion="23" android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

When I run cordova build android I get this error: Duplicated with element declared at AndroidManifest.xml

**Comment by iVanPan** [comment]
https://github.com/iVanPan/Cordova_QQ/issues/71
