### ISSUE TITLE
IOS中分享到QQ的问题，进入错误回调，但错误信息是null（使用的是0.3.4版本的插件，android机中转发正常）

### ISSUE THREAD

**Issue by Junting-Liu** [iVanPan/Cordova_QQ#76]
主要代码如下,      
 var args = {};
                args.url = this.removeFlag(share_url);
                args.title = share_title;
                args.description = share_desc;
                var imgs = [share_thumnail,
                    share_thumnail,
                    share_thumnail];
                args.imageUrl = imgs;
                YCQQ.shareToQzone(function () {     
                    console.log("Qzone share success");
                    statistics.templateStatistics(statisticsData(cus, "QQ空间"));
                }, function (failReason) {
                    console.log('error'+failReason);
                }, args);
在苹果机中转发到weibo也有相应问题。

**Comment by iVanPan** [comment]
@Junting-Liu  麻烦使用最新版本的插件，YCQQ 这个已经是老版本了。新版本我完全重写了一边，麻烦参照文档看一下 API 使用

**Comment by iVanPan** [comment]
@Junting-Liu  请尝试最新的 0.9.4 的版本
