### ISSUE TITLE
在安卓上QQ好友和空间都正常，但是在iOS上QQ好友正常，QQ空间在调用后会进分享界面，点击分享提示分享成功，之后弹出“未安装应用”的提示；

### ISSUE THREAD

**Issue by Skye27yang** [iVanPan/Cordova_QQ#78]
Before submitting issues ...

- 确保你的 App 在[腾讯开放平台](http://open.qq.com/)已审核通过.
- 如果是 Android 平台请确保你的apk签名是正确的.
- 请确认 demo 已测试通过.
- 请先搜索相关的 issues,看是否同样的问题已经有解决方案了.
- 发生出现错误码的情况，请前去腾讯开放平台咨询.

当你提交 issues 的时候, 请提供以下信息来帮助开发者更好的修复Bug:

- 开发环境: 插件版本, Cordova 版本, Xcode 版本.
- 如果出现错误，希望提供 Xcode 或 Android Studio 的错误日志.
- 如果有其他额外的信息，也希望可以提供一下，帮助我们更快的定位问题.

**Comment by Skye27yang** [comment]
QQ空间的代码：
function handleQQZoneShare(){
      var args = {};
      args.client = QQSDK.ClientType.QQ;
      args.scene = QQSDK.Scene.QQZone;
      args.url = $rootScope.share_page_url;
      args.title = $rootScope.share_title;
      args.description = $rootScope.share_description;
      args.image = $rootScope.share_img_url ;
      QQSDK.shareNews(function(){
      },function(failReason){
      },args);
    }

**Comment by iVanPan** [comment]
@Skye27yang  iPhone 6 Plus  iOS 10.3.3 Cordova版本是 7.0 插件版本是 0.9.6 我测试了一下并没有这个问题。是百分之百复现吗？

**Comment by Skye27yang** [comment]
是的，用了苹果5和苹果7测试都是失败的

**Comment by iVanPan** [comment]
未安装应用 是 QQ 客户端的提示？ 我装了最新的QQ 并没有这个问题 @Skye27yang  你用的是哪个版本的插件？

**Comment by iVanPan** [comment]
@Skye27yang 你用插件提供的 Demo 测试过吗？ 也有这个问题？

**Comment by Skye27yang** [comment]
QQ是最新版的，插件是0.9.6,版本，

**Comment by Skye27yang** [comment]
在QQ空间编辑分享界面，提示分享失败，应用不存在

**Comment by Skye27yang** [comment]
再iOS上分享到QQ空间很多次，就成功了一次 ，cordova是6.4.0

**Comment by iVanPan** [comment]
@Skye27yang  看一下 你的 URL Schemes 是不是正确的，我这边测试了很多遍都是可以的，无法复现你的问题

**Comment by Skye27yang** [comment]
首先看我的代码是没有问题的吧？在安卓上都是OK的，只有iOS的QQ空间不行，会不会是appid那个申请有问题呢？

**Comment by iVanPan** [comment]
@Skye27yang  也有可能 可以看一下是不是申请通过了，权限有没有

**Comment by Skye27yang** [comment]
发生了一个很诡异的现象，突然就成功了，不知道为啥，我们的账号是申请的安卓的应用，然后通过微下载链接（APP store下载地址等）上iOS的。
