### ISSUE TITLE
分享到QQ空间有时候会报错shareToQzone() MSG_PARAM_IMAGE_URL_FORMAT_ERROR--end，No permission to write APN settings是怎么回事？

### ISSUE THREAD

**Issue by Skye27yang** [iVanPan/Cordova_QQ#79]
Before submitting issues ...

- 确保你的 App 在[腾讯开放平台](http://open.qq.com/)已审核通过.
- 如果是 Android 平台请确保你的apk签名是正确的.
- 请确认 demo 已测试通过.
- 请先搜索相关的 issues,看是否同样的问题已经有解决方案了.
- 发生出现错误码的情况，请前去腾讯开放平台咨询.

当你提交 issues 的时候, 请提供以下信息来帮助开发者更好的修复Bug:

- 开发环境: 插件版本, Cordova 版本, Xcode 版本.
- 如果出现错误，希望提供 Xcode 或 Android Studio 的错误日志.
- 如果有其他额外的信息，也希望可以提供一下，帮助我们更快的定位问题.

**Comment by Skye27yang** [comment]
还有，我想知道我们分享news的时候的四个参数哪些为空的时候是会报错的？

**Comment by xushuo** [comment]
兄台。这个错误解决了么？
