### ISSUE TITLE
使用最新版本的shareNews，分享到qq空间时报错。

### ISSUE THREAD

**Issue by Junting-Liu** [iVanPan/Cordova_QQ#81]
代码如下：
let args = {};
        args.client = QQSDK.ClientType.QQ;
        args.scene =  QQSDK.Scene.QQZone;//QQSDK.Scene.QQZone,QQSDK.Scene.Favorite
        args.url = this.props.webpageUrl;
        args.title = this.props.title;
        args.description = this.props.description;
        args.image = this.props.thumb;
       QQSDK.shareNews(function () {
                this.props.sucCustomHandler({type: 'QQ空间'})
            }, function (reason) {
                alert(reason)
                console.log('QQ空间' + reason);
            }, args);
  同一段代码scene为QQ时正常，但scene为 QQZone时会报错。报错如下：Attemp to invoke virtual method ‘boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat,int,java.io.OutputStream)’on a null object refrence

**Comment by iVanPan** [comment]
@Junting-Liu  感谢你的反馈，请问运行项目demo有没有问题？尝试换一个图片试试，我现在手头没有 Android 手机 不好测试，等我有时间我会测试一下。

**Comment by Junting-Liu** [comment]
@iVanPan 感谢回复，demo运行正常，换成demo的图片后，我的代码也运行正常。
但还是想问一下，同一张图片为什么会出现转发QQ可以，但是Qzone不可以的情况？

**Comment by iVanPan** [comment]
这个我也不清楚，可能是更新SDK的缘故，具体需要调试一下才知道，方便的话，希望提供一下图片数据，十分感谢 @Junting-Liu

**Comment by Junting-Liu** [comment]
十分抱歉，图片资源被同事改动过，才导致了我这里的错误，与您的插件并无关系，耽误您时间了。十分十分抱歉。
