### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by WeiStatham** [iVanPan/Cordova_QQ#86]
cordova-andorid6.3.0 无法添加插件，要求cordova-android7.0.0

**Comment by iVanPan** [comment]
@WeiStatham  固定版本 用 0.9.6 的版本就可以了，0.9.7 和 0.9.6 的代码是一样的，配置不同而已

**Comment by wangyanchen** [comment]
怎么添加0.9.6版本的插件呢
