### ISSUE TITLE
cordova-android version is not support

### ISSUE THREAD

**Issue by q986171791** [iVanPan/Cordova_QQ#87]
npm info

Requirements

Cordova Version 3.5+
**Cordova-Android >= 4.0**
Cordova-iOS >= 4.0

github info

Requirements

Cordova Version 3.5+
**Cordova-Android >= 7.0**
Cordova-iOS >= 4.0

but I need cordova-android >= 4.0 
How to resolve?

**Comment by iVanPan** [comment]
https://github.com/iVanPan/Cordova_QQ/issues/86
