### ISSUE TITLE
发布插件到npm

### ISSUE THREAD

**Issue by Hybrid-Force** [iVanPan/Cordova_QQ#9]
感谢 @iVanPan 给大家分享了这个非常棒的插件！
由于国内的网络环境问题，用cordova cli直接从github安装插件的时间比较长。能否麻烦你将这个插件发布到npm呢？这样可以使安装的耗时缩短。
非常感谢！

**Comment by iVanPan** [comment]
@Hybrid-Force  感谢你的关注，我会尽快发布上去。

**Comment by iVanPan** [comment]
@Hybrid-Force  @21paradox 已经发布到npm上面，可以使用cordova plugin add cordova-plugin-qqsdk --variable QQ_APP_ID=YOUR_QQ_APPID 命令来添加插件。

**Comment by Hybrid-Force** [comment]
:+1:

**Comment by 21paradox** [comment]
非常感谢！
