### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by CjoyHome** [iVanPan/Cordova_QQ#90]
Installing "cordova-plugin-qqsdk" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.0.0
Skipping 'cordova-plugin-qqsdk' for android
Adding cordova-plugin-qqsdk to package.json
Saved plugin info for "cordova-plugin-qqsdk" to config.xml
请问这个问题怎么解决？

**Comment by CjoyHome** [comment]
cordova -v
7.1.0

**Comment by iVanPan** [comment]
你的cordova-android 是6.3的版本 新版本插件要求是7.0
