### ISSUE TITLE
直接就上cordova android7.0.0  我的项目才cordova android6.4.0 没有办法使用了。大神求解答，急。

### ISSUE THREAD

**Issue by JackSparrow1937** [iVanPan/Cordova_QQ#93]
Before submitting issues ...

- 确保你的 App 在[腾讯开放平台](http://open.qq.com/)已审核通过.
- 如果是 Android 平台请确保你的apk签名是正确的.
- 请确认 demo 已测试通过.
- 请先搜索相关的 issues,看是否同样的问题已经有解决方案了.
- 发生出现错误码的情况，请前去腾讯开放平台咨询.

当你提交 issues 的时候, 请提供以下信息来帮助开发者更好的修复Bug:

- 开发环境: 插件版本, Cordova 版本, Xcode 版本.
- 如果出现错误，希望提供 Xcode 或 Android Studio 的错误日志.
- 如果有其他额外的信息，也希望可以提供一下，帮助我们更快的定位问题.

**Comment by gdongy** [comment]
解决了吗，我的是6.3.0的，也用不了啊

**Comment by zzhDmon** [comment]
是必须cordova-android7.0.0以上，有低版本的吗

**Comment by ryanlin1986** [comment]
使用历史版本不就好了嘛，如0.9.4
